version: '{build}'
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

nuget:
  disable_publish_on_pr: true

before_build:
  - cmd: dotnet restore

after_build:
- dotnet pack "src\Narochno.Primitives" -c Release
- dotnet pack "src\Narochno.Primitives.Json" -c Release

test_script:
- dotnet test "test\Narochno.Primitives.Tests\Narochno.Primitives.Tests.csproj"
- dotnet test "test\Narochno.Primitives.Json.Tests\Narochno.Primitives.Json.Tests.csproj"

artifacts:
- path: src\Narochno.Primitives\bin\Release\*.nupkg
- path: src\Narochno.Primitives.Json\bin\Release\*.nupkg

deploy:
  - provider: Environment
    name: nuget.org
    on:
      branch: master
