version: '{build}'

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

nuget:
  disable_publish_on_pr: true

before_build:
  - cmd: dotnet restore

after_build:
- dotnet pack "src\Narochno.Primitives\project.json" -c Release
- dotnet pack "src\Narochno.Primitives.Json\project.json" -c Release
- dotnet pack "src\Narochno.Primitives.Parsing\project.json" -c Release

test_script:
- dotnet test "test\Narochno.Primitives.Tests" -c Release
- dotnet test "test\Narochno.Primitives.Json.Tests" -c Release
- dotnet test "test\Narochno.Primitives.Parsing.Tests" -c Release

artifacts:
- path: src\Narochno.Primitives\bin\Release\*.nupkg
- path: src\Narochno.Primitives.Json\bin\Release\*.nupkg

deploy:
  - provider: Environment
    name: nuget.org
    on:
      branch: master
