name: Narochno.Primitives
on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    - run: dotnet run --project build/build.csproj
    - uses: actions/upload-artifact@v4
      with:
        name: narochno.primitives.nupkg
        path: artifacts/*
